### ISSUE TITLE
swift template compile errors

### ISSUE THREAD

**Issue by makk94** [preludeorg/libraries#114]
```
mahinakaholokula@Mahinas-MacBook-Pro ~ % prelude build run 839509f6-5864-4b07-9633-300c20fd8968.swift
[
  {
    "name": "839509f6-5864-4b07-9633-300c20fd8968_darwin-x86_64",
    "steps": [
      {
        "step": "COMPILE",
        "status": 1,
        "output": "<unknown>:0: error: unable to load standard library for target 'x86_64-apple-macos10.15'\n",
        "duration": "0.175"
      }
    ]
  },
  {
    "name": "839509f6-5864-4b07-9633-300c20fd8968_darwin-arm64",
    "steps": [
      {
        "step": "COMPILE",
        "status": 1,
        "output": "<unknown>:0: error: unable to load standard library for target 'arm64-apple-macos10.15'\n",
        "duration": "0.182"
      }
    ]
  }
]
```

**Comment by makk94** [comment]
https://www.swift.org/platform-support/
https://www.swift.org/server/guides/building.html

> Swift binaries are architecture-specific, so running the build command on macOS will create a macOS binary, and similarly running the command on Linux will create a Linux binary.



Options:
- Run compute on a macos base
  - We could still compile for linux on a macos base (via docker or via swiftpm which has [cross compilation support](https://github.com/apple/swift-package-manager/pull/1098) ([example script](https://github.com/apple/swift-package-manager/blob/main/Utilities/build_ubuntu_cross_compilation_toolchain)) - don't see a way to use this cross compilation in the other direction since I can't find a macos library for ubuntu)

**Comment by mireaulf** [comment]
Closing the issue for now as the compute service needs support for darwin STL
