### ISSUE TITLE
darwin-arm64.c test is killed by MacOS

### ISSUE THREAD

**Issue by jaherne** [preludeorg/libraries#115]
After saving and downloading the Darwin Arm64 C template for MacOS, the resulting executable is killed when ran with a 137 return code. This is generating a crash dump on an M1 Mac:

`Exception Type:  EXC_BAD_ACCESS (SIGKILL (Code Signature Invalid))`

This is not reproducible when using a universal or x86_64 test. The full crash dump is attached: [test-2022-11-17-223522.txt](https://github.com/preludeorg/libraries/files/10038788/test-2022-11-17-223522.txt)

**Comment by privateducky** [comment]
good find/report

**Comment by mireaulf** [comment]
This looks related to https://github.com/preludeorg/libraries/issues/114

**Comment by makk94** [comment]
Probably not related @mireaulf  - #114 is about compiling swift, this one is running an already compiled executable

**Comment by jaherne** [comment]
Going to close this out - I am not able to reproduce in a clean environment. I think errors were being thrown given the rate I was updating `/tmp/test` in my environment.
