### ISSUE TITLE
CLI configure is not working

### ISSUE THREAD

**Issue by privateducky** [preludeorg/libraries#128]
Two scenarios, both failing:
- existing keychain file (nothing overrides)
- no keychain file (image below)

<img width="600" alt="Screenshot 2022-11-28 at 7 38 50 AM" src="https://user-images.githubusercontent.com/49954156/204280058-0d038a12-1295-4ae8-a887-da768fdf11ea.png">

**Comment by privateducky** [comment]
One of these may be occurring only when your keychain has multiple entries, as starting with a single keychain entry resets properly.

**Comment by makk94** [comment]
Note: to repro scenario 2:
have no keychain file, and then do `prelude configure` with a non-"default" profile as the first configured profile
