### ISSUE TITLE
CLI issues on windows

### ISSUE THREAD

**Issue by makk94** [preludeorg/libraries#158]
CLI commands that are interactive (ex. `prelude build create-variant`) just hang instead of showing the expected prompts (`what platform do you want`, etc)

Was on windows_x86-64

**Comment by mireaulf** [comment]
Cannot reproduce on my Windows 11 box. Were you using a VM?

**Comment by mireaulf** [comment]
Which version of windows is it running?

**Comment by makk94** [comment]
ooh actually it works in cmd and powershell. It only hangs in Powershell ISE, which is weird, but probably not important for us to figure out

Closing
