### ISSUE TITLE
Improve graceful error-handling for deprecated CLI commands

### ISSUE THREAD

**Issue by nsreidy2** [preludeorg/libraries#163]
In prelude-cli v0.9.16 there was a valid command "prelude iam update-token"
This command appears to have been deprecated in v0.9.17.
When I ran the command, it threw two Exceptions, with the last line of the first one being "Exception: 405: Method Not Allowed"

The next line was "During handling of the above exception, another exception occurred:"

And then another exception/stacktrace was listed.

When we deprecate (or substantially change) commands on the server-side, it would be nice if a clean/graceful error message were thrown to the CLI. Eg. "That command is no longer supported or the arguments have been changed. Please update your prelude-cli to the latest version with 'pip install -U prelude-cli'"

**Comment by makk94** [comment]
@privateducky I don't see any python click options to handle deprecation nicely, which means that it'd just have to be a conscious choice for us to stop deleting commands and instead return a `Deprecated method` response from our backend (or the CLI frontend) for X weeks/months. Is the nice deprecation message worth the extra maintenance?

**Comment by privateducky** [comment]
Yea it's pretty nuanced, so I'd say no.
If there's an overall "this is not a valid command" handler in click, that'd be worthwhile though.
