### ISSUE TITLE
docs do not explain account/token requirements

### ISSUE THREAD

**Issue by VVX7** [preludeorg/libraries#20]
The readme doesn't explain what the account and token are, how to generate them, or validate the input as a UUID/token/etc.

```
❯ prelude configure
Enter the profile name [default]: 
Enter the Prelude API [https://detect.prelude.org]: 
Enter your account ID: foo
Enter your account token: what even is this
Credentials saved
```

**Comment by privateducky** [comment]
should be solved auto through https://github.com/preludeorg/libraries/issues/19
