### ISSUE TITLE
Occasional bug with Windows installer

### ISSUE THREAD

**Issue by privateducky** [preludeorg/libraries#207]
There is an occasional bug in the Windows installer. It is not known yet what systems are impacted.

**Comment by mireaulf** [comment]
What is the bug?

**Comment by makk94** [comment]
Closing in favor of splitting out into https://github.com/preludeorg/libraries/issues/213 and https://github.com/preludeorg/libraries/issues/212

If you're aware of other bugs, open new ones w/ specifics please
