### ISSUE TITLE
Probes should all match on timeout behavior

### ISSUE THREAD

**Issue by privateducky** [preludeorg/libraries#261]
Shell probes currently run w/out a timeout enabled while the language probes enforce a 2s timeout. 

Let's extend this to 10s across all probes.

Documentation likely needs to be updated as well.

**Comment by khyberspache** [comment]
Some options:
1. support "remote config" with defaults in the probe
2. just hardcode 10s in code

**Comment by privateducky** [comment]
LOL. so many confusing options, I don't think I can absorb them all :) 
I've also been thinking of the remote config idea -- via a special test, potentially. wonder if we could tie this into probe updating in general, which is on the roadmap.

**Comment by privateducky** [comment]
While we kick this around, let's at least get all probes to a baseline of no internal timeout. 

Additionally, let's look at adding a timeout of 10s to the Endpoint.Start function (kick off a go routine) in the test repo.

**Comment by mireaulf** [comment]
What do you mean by timeout? Time between executing each test or time between fetching tests?

**Comment by privateducky** [comment]
time running each test
