### ISSUE TITLE
Auth failure when user with BUILD permissions uses token generated under my account

### ISSUE THREAD

**Issue by bfuzzy1** [preludeorg/libraries#287]
Running into an auth failure when internal-octavia who has BUILD permissions under my account attempts to use the token that is generated by prelude-cli.

<img width="403" alt="Screenshot 2023-01-27 at 4 38 22 PM" src="https://user-images.githubusercontent.com/54591490/215213478-e47bb314-fcf1-49d2-85ab-7187f65b91f2.png">

<img width="724" alt="CleanShot 2023-01-27 at 16 10 56@2x" src="https://user-images.githubusercontent.com/54591490/215213541-5e14f9f7-7d1b-4ae9-97e2-5ce574723006.png">

**Comment by makk94** [comment]
hm.. I can't repro this problem by myself (in staging or prod)

can you double check:
- both using the same env (prod or staging)
- both have the same account_id

if it's neither of those things - lmk and I'd like to try to repro with you @bfuzzy1

**Comment by makk94** [comment]
Confirmed with bfuzzy and octavia that it's working for them now
Closing
