### ISSUE TITLE
Windows Install.ps1 fails when running as NT AUTHORITY/SYSTEM

### ISSUE THREAD

**Issue by khyberspache** [preludeorg/libraries#330]
receiving this error if the installation is run as the SYSTEM user:

```
Register-ScheduledTask : No mapping between account names and security IDs was done. (14,8):UserId:
At C:\\Windows\\system32\\install.ps1:69 char:12
+     [void](Register-ScheduledTask -TaskName $name -InputObject $task)
+            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : NotSpecified: (PS_ScheduledTask:Root/Microsoft/...S_ScheduledTask) [Register-ScheduledTask], CimException
+ FullyQualifiedErrorId : HRESULT 0x80070534,Register-ScheduledTask
```

**Comment by makk94** [comment]
Thought it was okay to require that an administrator run the install script?

**Comment by mireaulf** [comment]
@khyberspache What's the output of `$env:UserDomain` and `$env:UserName`?

Could you edit the install script and change the following line
`$principal = New-ScheduledTaskPrincipal -LogonType S4U -UserId "$env:UserDomain\$env:UserName"`
to
`$principal = New-ScheduledTaskPrincipal -UserId "$env:UserDomain\$env:UserName" -LogonType ServiceAccount -RunLevel Highest` and tell me if there is a difference in the output or if it worked?

It's really hard to debug that via an intermediate :/

**Comment by khyberspache** [comment]
> @khyberspache What's the output of `$env:UserDomain` and `$env:UserName`?
> 
> Could you edit the install script and change the following line `$principal = New-ScheduledTaskPrincipal -LogonType S4U -UserId "$env:UserDomain\$env:UserName"` to `$principal = New-ScheduledTaskPrincipal -UserId "$env:UserDomain\$env:UserName" -LogonType ServiceAccount -RunLevel Highest` and tell me if there is a difference in the output or if it worked?
> 
> It's really hard to debug that via an intermediate :/

Yes I can run these - I can also give you access to the system if you want

**Comment by khyberspache** [comment]
<img width="1063" alt="CleanShot 2023-02-10 at 08 25 21@2x" src="https://user-images.githubusercontent.com/43142871/218103074-cea9ebb7-1be1-49f6-8f3e-2022b4ec5746.png">

**Comment by khyberspache** [comment]
@mireaulf I swapped to `$principal = New-ScheduledTaskPrincipal -UserId "$env:UserDomain\$env:UserName" -LogonType ServiceAccount -RunLevel Highest`
<img width="981" alt="CleanShot 2023-02-10 at 08 30 31@2x" src="https://user-images.githubusercontent.com/43142871/218104126-419e8604-89fb-4add-973a-f833ee77a5fc.png">

**Comment by khyberspache** [comment]
https://github.com/preludeorg/libraries/pull/336

**Comment by privateducky** [comment]
> Thought it was okay to require that an administrator run the install script?

Correct; Administrator can be expected to do a probe installation (although the probe itself should run as user).
