### ISSUE TITLE
Windows doesn't clean up VST's from tmp until restart

### ISSUE THREAD

**Issue by gerbsec** [preludeorg/libraries#332]
While Linux and MacOS have some functionality to clean up their respective TMP directories, windows will hoard onto its precious tmp directory until a restart occurs, which is often rare for server. This means that 100 tests later == 100 vsts in tmp just chilling there.

Random but also related, on linux and mac, using nocturnal, you can see not only the tmp vst's but also empty temp files. it seems like mktemp went through but a vst was not written to it.  same happens with raindrop.

**Comment by privateducky** [comment]
Two distinct things here.

For the first, no Windows cleanup, we should adjust all probes to remove tests after executing them.

For the second, we need to investigate why this is.

**Comment by makk94** [comment]
both of these just come down to "we don't clean up VSTs explicitly in probes"

(the second happens because we create the tempfile before we actually know if there's a test to write to it yet, so when there are no tests returned, you just get an empty file before the probe goes to sleep)

**Comment by privateducky** [comment]
ah, makes sense. 
so adding the explicit test removal should do the trick.

**Comment by privateducky** [comment]
I noticed raindrop is creating temp files before even retrieving a test. 
We should only create the temp file if a test is retrieved.

**Comment by makk94** [comment]
I think it's the opposite. Nocturnal creates the temp files before retrieving the test. Raindrop doesn't I don't think

**Comment by privateducky** [comment]
> I think it's the opposite. Nocturnal creates the temp files before retrieving the test. Raindrop doesn't I don't think

That's possible, but let's verify that. I see this at the very beginning of raindrop, which I believe will create a new file in Windows. This occurs before the request to Service:
```
function Run {
    Param([String]$Dat = "")

    $TempFile = [System.IO.Path]::GetTempFileName() | Rename-Item -NewName { [System.IO.Path]::ChangeExtension($_, "exe") } -PassThru
...
```

**Comment by makk94** [comment]
Ah yeah youre right. In my choose-download-directory PR I had changed it to stop creating the temp files before getting the test. But that didn't actually get merged

I'll separate that logic out into a new PR
