### ISSUE TITLE
probe installed via install script doesnt restart on reboots [windows 2016]

### ISSUE THREAD

**Issue by makk94** [preludeorg/libraries#334]
Task runs/works when I first install, on reboot, the scheduledtask fails to start:

![Screen Shot 2023-02-09 at 10 26 45 AM](https://user-images.githubusercontent.com/9056078/217904261-97a883c1-4d05-4a0a-a012-1ed78ca134ab.png)

This happens on `Windows_Server-2016-English-Full-Base-2023.01.19`
Does not happen on windows 2022 base

**Comment by makk94** [comment]
In event logs, before the `failed to start task` log, I have this:
```
Task Scheduler failed to log on "\Prelude Detect" . Failure occurred in "LogonUserS4U" . User Action: Ensure the credentials for the task are correctly specified. Additional Data: Error Value: 2147943711.
```

**Comment by khyberspache** [comment]
We are moving off scheduled tasks so this will be resolved through deprecation
