### ISSUE TITLE
Windows demo probe installation "Register-ScheduledTask: Access is denied" error

### ISSUE THREAD

**Issue by nsreidy2** [preludeorg/libraries#337]
1) visited https://platform.preludesecurity.com/probe/demo
2) registered account in top-right
3) clicked Windows, copied command, ran in Powershell
4) got "Register-ScheduledTask: Access is denied" error

![image](https://user-images.githubusercontent.com/118935081/218156795-56203bae-008c-4808-b70e-450bded6c3c7.png)

**Comment by nsreidy2** [comment]
OS is Windows 11

**Comment by mireaulf** [comment]
Are you running your powershell prompt as admin? Right-click on powershell and select "Run as admin", try again and let me know if that works.

**Comment by nsreidy2** [comment]
Hi, thanks, yes that worked.

We should add instructions so that people know to do that, and we might
consider more graceful error messaging.

**Comment by privateducky** [comment]
Closing, as this is a documentation/description "thing". We will improve that on the next iteration on the platform (hopefully out next week).
