### ISSUE TITLE
CLI coloring in windows is not great

### ISSUE THREAD

**Issue by makk94** [preludeorg/libraries#342]
![Screen Shot 2023-02-13 at 8 31 02 AM](https://user-images.githubusercontent.com/9056078/218515613-f5f68e56-f200-45f8-b218-162e30ca95bd.png)

**Comment by privateducky** [comment]
ouch

**Comment by makk94** [comment]
The click library has limited color options available

The one that fixes this issue is to turn color off. I plan to do that unless someone reading this issue is super attached to color in our CLI

**Comment by mireaulf** [comment]
Add documentation for that and that's good enough - no code is the best code

**Comment by makk94** [comment]
![Screenshot 2023-02-17 at 9 35 24 AM](https://user-images.githubusercontent.com/9056078/219727509-b695d0cc-e343-478a-baa4-d2c45a1bf767.png)

Added to docs. Closing
