### ISSUE TITLE
Probe backoff after invalid token

### ISSUE THREAD

**Issue by mireaulf** [preludeorg/libraries#359]
Linked to https://github.com/preludeorg/roadmap/issues/4

Probes should backoff for a delay (24 hours) if they get an `invalid token` response from the api.

**Comment by privateducky** [comment]
what is the behavior right now, it'll sleep for 4 hours on an auth failure?
if so, I don't see the need to add logic just for the extra time. I'd be more inclined to add logging/alerting on AWS so we can relay that info to the endpoint owner quicker.
