### ISSUE TITLE
build upload does not handle paths and binary files correctly

### ISSUE THREAD

**Issue by VVX7** [preludeorg/libraries#374]
`prelude build upload <path>` returns an error when pointing it at a path or a binary file.

Expected: 
The cli complains that the file type is not supported or a path to a file must be used.

Actual:
`utf-8` error mesage.

<img width="726" alt="CleanShot 2023-02-23 at 10 23 15@2x" src="https://user-images.githubusercontent.com/46228229/220950897-e228da7a-aaee-4859-a2a6-ef51db651359.png">

**Comment by privateducky** [comment]
This should be solved when the new "wizard" PR is merged in (shortly).

**Comment by privateducky** [comment]
@VVX7 can you retest?

**Comment by VVX7** [comment]
Yep, working as expected! 
<img width="727" alt="CleanShot 2023-03-15 at 10 54 34@2x" src="https://user-images.githubusercontent.com/46228229/225348695-244abb4a-74d0-41d7-8ced-b831e77ea23d.png">
