### ISSUE TITLE
Improvement - CLI should not be case sensitive for Endpoint ID

### ISSUE THREAD

**Issue by PeteC-Prelude** [preludeorg/libraries#415]
While using the CLI to query activity on a specific endpoint, I was getting no results.  Looks like the current CLI is case sensitive for endpoint id.  See screen caps below
![screenshot_65](https://user-images.githubusercontent.com/126490894/222779714-436d1197-5de8-488a-aacd-754de398ae67.png)
![screenshot_66](https://user-images.githubusercontent.com/126490894/222779721-7e99d557-c096-4d1f-871e-f73bd6feb699.png)

**Comment by mireaulf** [comment]
Ticket moved
