### ISSUE TITLE
multiple queue items with same test_id + null tag

### ISSUE THREAD

**Issue by makk94** [preludeorg/libraries#448]
![image](https://user-images.githubusercontent.com/9056078/225110499-65b20143-0055-47ac-aca8-00caedd6ab88.png)

repro:
- add a test to the queue with null tags
- try to change that test's run_code -> it'll just add another queue item instead

notes:
- only happens with null tags

**Comment by privateducky** [comment]
this is expected; these are schedules that have no tag filter

**Comment by privateducky** [comment]
> sorry - bad title (updating it)
> 
> the bug is that two of the tests have the same id (ie we're adding a row not updating when tag is null even though the test is already in the queue)

Ah, I see -- two different run codes.

**Comment by gerbsec** [comment]
Even when you don't change run code, it'll add a new one:
<img width="530" alt="image" src="https://user-images.githubusercontent.com/67713732/225953267-6b9d25d9-ca5f-45ec-8acc-c333bd54d5e4.png">

**Comment by privateducky** [comment]
@mireaulf ideas?
