### ISSUE TITLE
Interactive - toggling through users to delete

### ISSUE THREAD

**Issue by harry-prelude** [preludeorg/libraries#458]
Toggling up/down through my list of potentially delete-able users in Interactive mode

https://user-images.githubusercontent.com/120492853/225691684-ea28b5c4-7d38-4ff7-8d12-7852e23db946.mov

**Comment by mireaulf** [comment]
Which version of the cli are you using?

**Comment by harry-prelude** [comment]
It was .92, I've updated to .93 and am still seeing this behavior.

**Comment by privateducky** [comment]
@mireaulf ideas?

**Comment by mireaulf** [comment]
I can repro, it's not quite straightforward to fix
