### ISSUE TITLE
error handling: better 403 error message

### ISSUE THREAD

**Issue by makk94** [preludeorg/libraries#83]
Currently get 
`Unauthorized. https://docs.prelude.org/v2/docs/prelude-account-1`

Would be nice to have a fuller message along the lines of "you have X permissions and command Y requires Z permissions" or something

(technically Z there can be figured out through docs, but it's not possible to figure out X unless you're admin)

**Comment by mireaulf** [comment]
That's interesting, how would you make that available in the cli and keeping it in sync with the backend?

**Comment by makk94** [comment]
I'd have the backend return the proper error message
(i'm lazily adding all my issues to this repo, but the fixes won't always be there)

**Comment by privateducky** [comment]
let's do a 1/2 solution: return the user's current permission. so the msg would be:
```
Unauthorized. {PERM} permission not high enough (https://docs.prelude.org/v2/docs/prelude-account-1)
```
