### ISSUE TITLE
Partner API response questionable for detachment.

### ISSUE THREAD

**Issue by chrishalbert** [preludeorg/libraries#925]
In efforts to get familiar with Prelude, I decided to incorporate some pytests. I noticed there wasn't any test coverage on the `partner_controller.py` (and probably for good reason, given the need for auth), but I decided to add negative tests either way. While I was testing against the prelude api on my test account, I found what seems to be an inconsistency in the responses.

If I try to `attach` a partner with invalid credentials, I will get failure from the api. ✅ 
If I try to `block` a test for a partner that I have not attached, I will get a failure from the api. ✅ 
Now, if I try to `detach` a partner that I have not attached, I will get a valid 200 response with `{status:True}`. ❓ 

I do want to note that this is a `delete` operation vs the `post` operation and it may just return a true status if the data store delete does not fail. This may be the intended behavior, but I wasn't able to confirm either way - I tried to look for the the prelude api docs for the final say.

**Comment by chrishalbert** [comment]
Here is a [PR](https://github.com/preludeorg/libraries/pull/926) for the negative cases on the `partner_controller.py`.

Please feel free to edit, request changes/additions, or decline if you wish 😄

**Comment by matterpreter** [comment]
Thanks for the report and PR @chrishalbert! Closing this out as it was addressed in #953 as discussed in the comments on #926.
