### ISSUE TITLE
go probe needs some updates

### ISSUE THREAD

**Issue by makk94** [preludeorg/libraries#98]
The Go probe is not fully consistent with Moonlight (the template).

At the least, we should:
- line up the environment variables that Go probe uses to what Swift probe uses
- the run function still thinks the test function runs by calling the executable with a cmd line arg "test" (vs now the test function runs when there are no cmd line args)
- nit: "cleanup" is now "clean" everywhere else

**Comment by privateducky** [comment]
@khyberspache can you help on this one?
